### ISSUE TITLE
no pre_mimic.py

### ISSUE THREAD

**Issue by jdjmoon** [ruoqi-liu/DSW#2]
Hello, I was not able to find pre_mimic.py. I was wondering if the file may have been deleted or if it is yet to be shared. Thank you.

**Comment by ruoqi-liu** [comment]
- pre_mimic.py is to preprocess MIMIC III data. It is similar to simulate_mimic.py but uses real treatments and outcomes instead of simulated treatments and outcomes.

Specifically: 
- We obtain the vasopressor assignments (vasopressor_durations) according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/vasopressor_durations.sql

- We obtain the ventilator assignments (ventilation_durations) according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/ventilation_durations.sql

- We obtain values of Meanbp and SpO2, which are vital signs according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted_vital.sql

**Comment by ruoqi-liu** [comment]
> Hello, I was not able to find pre_mimic.py. I was wondering if the file may have been deleted or if it is yet to be shared. Thank you.

Hi, 
- pre_mimic.py is to preprocess MIMIC III data. It is similar to simulate_mimic.py but uses real treatments and outcomes instead of simulated treatments and outcomes.

Specifically:

- We obtain the vasopressor assignments (vasopressor_durations) according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/vasopressor_durations.sql

- We obtain the ventilator assignments (ventilation_durations) according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/durations/ventilation_durations.sql

- We obtain values of Meanbp and SpO2, which are vital signs according to https://github.com/MIT-LCP/mimic-code/blob/master/concepts/pivot/pivoted_vital.sql

**Comment by TianyiChen97** [comment]
https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iii/concepts/durations/vasopressor_durations.sql

**Comment by TianyiChen97** [comment]
> https://github.com/MIT-LCP/mimic-code/blob/main/mimic-iii/concepts/durations/vasopressor_durations.sql

This is the new link for the above links, they change the directory a little.

**Comment by TianyiChen97** [comment]
Hi, I am wondering in simulate_mimic.py, where does  "icu_hadm_dict.json" come from at the beginning of your code. 
And I am assuming lines 13-15 are for extracting only icustay patients' data for analysis, correct? Thanks.

**Comment by ruoqi-liu** [comment]
> Hi, I am wondering in simulate_mimic.py, where does "icu_hadm_dict.json" come from at the beginning of your code.
> And I am assuming lines 13-15 are for extracting only icustay patients' data for analysis, correct? Thanks.

icu_hadm_dict.json contains the mapping of “ICUSTAY_ID” to “HADM_ID”. We obtain the sepsis-3 cohort and patients’ IDs using this toolkit (https://github.com/alistairewj/sepsis3-mimic/tree/v1.0.0).

**Comment by WEIQIAN17** [comment]
> icu_hadm_dict.json contains the mapping of “ICUSTAY_ID” to “HADM_ID”. We obtain the sepsis-3 cohort and patients’ IDs using this toolkit (https://github.com/alistairewj/sepsis3-mimic/tree/v1.0.0).

Hi, I have a question about icu_hadm_dict.json. Is it sepsis-3 cohort in the [sepsis3-mimic](https://github.com/alistairewj/sepsis3-mimic/tree/v1.0.0)/sepsis-3-get-data.ipynb. And it is generated by 
https://github.com/alistairewj/sepsis3-mimic/blob/v1.0.0/query/tbls/cohort.sql
https://github.com/alistairewj/sepsis3-mimic/blob/v1.0.0/query/tbls/sepsis3.sql. Thanks.
